#parrotOS Dockerfile 
FROM parrotsec/core:rolling

#Install components
RUN apt-get update; apt-get -y dist-upgrade;apt-get -y install parrot-pico;apt-get -y install parrot-mini parrot-tools-cloud; apt install xrdp; rm -rf /var/lib/apt/lists/*; service start xrdp

#Expose xrdp port
EXPOSE 3390/tcp
